# Generated by Django 5.0.1 on 2024-01-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0002_alter_message_profile_id_alter_message_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
