# Generated by Django 5.0.1 on 2024-01-11 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0003_message_message_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_body',
        ),
    ]
