# Generated by Django 5.0.1 on 2024-01-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0007_pendingrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrequest',
            name='message',
            field=models.TextField(default=' '),
        ),
    ]
