# Generated by Django 5.0.1 on 2024-01-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0009_alter_friendship_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingrequest',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
