# Generated by Django 5.0.1 on 2024-01-13 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0011_alter_pendingrequest_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='chat_background',
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='message',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
