# Generated by Django 5.0.1 on 2024-01-13 03:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0013_remove_profile_profile_id_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='messager.friendship'),
        ),
    ]
