# Generated by Django 5.0.1 on 2024-01-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0015_blacklistedusers'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
