# Generated by Django 5.0.1 on 2024-03-04 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0017_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
