# Generated by Django 5.0.1 on 2024-03-06 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0018_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
