# Generated by Django 4.0.1 on 2024-06-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messager', '0019_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingrequest',
            name='token',
            field=models.TextField(default=''),
        ),
    ]
